[package]
name = "rust-sushi-futures-example"
version = "0.1.0"
authors = ["Lukasz Piatkowski <lukaspiatkowski@gmail.com>"]
edition = "2018"

[dependencies]

env_logger = "0.7.1"
futures = "0.3.1"
log = "0.4.8"
quickcheck = "0.9.2"
rand = "0.7.3"
tokio = { version = "0.2.10", features = ["full"] }
